[2025-03-14T12:24:06.558+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T12:24:06.575+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parse_mongo_to_sql_dag.parse_fallacies manual__2025-03-14T12:24:03.606141+00:00 [queued]>
[2025-03-14T12:24:06.582+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parse_mongo_to_sql_dag.parse_fallacies manual__2025-03-14T12:24:03.606141+00:00 [queued]>
[2025-03-14T12:24:06.583+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 5
[2025-03-14T12:24:06.596+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): parse_fallacies> on 2025-03-14 12:24:03.606141+00:00
[2025-03-14T12:24:06.602+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5917) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-14T12:24:06.603+0000] {standard_task_runner.py:72} INFO - Started process 5921 to run task
[2025-03-14T12:24:06.604+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'parse_mongo_to_sql_dag', 'parse_fallacies', 'manual__2025-03-14T12:24:03.606141+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/parse2mongo.py', '--cfg-path', '/tmp/tmp499uud7v']
[2025-03-14T12:24:06.607+0000] {standard_task_runner.py:105} INFO - Job 181: Subtask parse_fallacies
[2025-03-14T12:24:06.641+0000] {task_command.py:467} INFO - Running <TaskInstance: parse_mongo_to_sql_dag.parse_fallacies manual__2025-03-14T12:24:03.606141+00:00 [running]> on host 31c19d57802d
[2025-03-14T12:24:06.708+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parse_mongo_to_sql_dag' AIRFLOW_CTX_TASK_ID='parse_fallacies' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T12:24:03.606141+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-14T12:24:03.606141+00:00'
[2025-03-14T12:24:06.709+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T12:24:08.657+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-14T12:24:08.664+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T12:24:08.665+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=parse_mongo_to_sql_dag, task_id=parse_fallacies, run_id=manual__2025-03-14T12:24:03.606141+00:00, execution_date=20250314T122403, start_date=20250314T122406, end_date=20250314T122408
[2025-03-14T12:24:12.039+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-14T12:24:12.057+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-14T12:24:12.059+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
