[2025-03-14T10:46:26.497+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T10:46:26.542+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.first_task scheduled__2025-03-11T00:00:00+00:00 [queued]>
[2025-03-14T10:46:26.579+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.first_task scheduled__2025-03-11T00:00:00+00:00 [queued]>
[2025-03-14T10:46:26.581+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 5
[2025-03-14T10:46:26.764+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2025-03-11 00:00:00+00:00
[2025-03-14T10:46:26.807+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=233) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-14T10:46:26.810+0000] {standard_task_runner.py:72} INFO - Started process 252 to run task
[2025-03-14T10:46:26.853+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'first_task', 'scheduled__2025-03-11T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpupvafwha']
[2025-03-14T10:46:26.882+0000] {standard_task_runner.py:105} INFO - Job 105: Subtask first_task
[2025-03-14T10:46:27.106+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag.first_task scheduled__2025-03-11T00:00:00+00:00 [running]> on host 857b64da211c
[2025-03-14T10:46:27.355+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-11T00:00:00+00:00'
[2025-03-14T10:46:27.356+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T10:46:27.405+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-14T10:46:27.411+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo first task! This is something you should see in the logs']
[2025-03-14T10:46:27.438+0000] {subprocess.py:99} INFO - Output:
[2025-03-14T10:46:27.449+0000] {subprocess.py:106} INFO - first task! This is something you should see in the logs
[2025-03-14T10:46:27.450+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-14T10:46:27.527+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T10:46:27.530+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=first_task, run_id=scheduled__2025-03-11T00:00:00+00:00, execution_date=20250311T000000, start_date=20250314T104626, end_date=20250314T104627
[2025-03-14T10:46:27.638+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-14T10:46:27.811+0000] {taskinstance.py:3901} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-03-14T10:46:27.820+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
