[2025-03-13T16:15:35.700+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-13T16:15:35.716+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_scraping_dag.trigger_parse_dag manual__2025-03-13T15:52:01.509950+00:00 [queued]>
[2025-03-13T16:15:35.723+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_scraping_dag.trigger_parse_dag manual__2025-03-13T15:52:01.509950+00:00 [queued]>
[2025-03-13T16:15:35.724+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 5
[2025-03-13T16:15:35.735+0000] {taskinstance.py:2890} INFO - Executing <Task(TriggerDagRunOperator): trigger_parse_dag> on 2025-03-13 15:52:01.509950+00:00
[2025-03-13T16:15:35.741+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6990) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-13T16:15:35.742+0000] {standard_task_runner.py:72} INFO - Started process 6991 to run task
[2025-03-13T16:15:35.741+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_scraping_dag', 'trigger_parse_dag', 'manual__2025-03-13T15:52:01.509950+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/Website2mongo.py', '--cfg-path', '/tmp/tmput9kngpd']
[2025-03-13T16:15:35.743+0000] {standard_task_runner.py:105} INFO - Job 143: Subtask trigger_parse_dag
[2025-03-13T16:15:35.780+0000] {task_command.py:467} INFO - Running <TaskInstance: web_scraping_dag.trigger_parse_dag manual__2025-03-13T15:52:01.509950+00:00 [running]> on host 40f8d416e5ba
[2025-03-13T16:15:35.850+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_scraping_dag' AIRFLOW_CTX_TASK_ID='trigger_parse_dag' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T15:52:01.509950+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-13T15:52:01.509950+00:00'
[2025-03-13T16:15:35.852+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-13T16:15:36.029+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 16:15:35.869727+00:00 to become allowed state ['success'] ...
[2025-03-13T16:16:41.497+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 16:15:35.869727+00:00 to become allowed state ['success'] ...
[2025-03-13T16:17:46.967+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 16:15:35.869727+00:00 to become allowed state ['success'] ...
[2025-03-13T16:18:52.435+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 16:15:35.869727+00:00 to become allowed state ['success'] ...
[2025-03-13T16:19:57.903+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 16:15:35.869727+00:00 to become allowed state ['success'] ...
[2025-03-13T16:21:03.372+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 16:15:35.869727+00:00 to become allowed state ['success'] ...
[2025-03-13T16:22:08.839+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 16:15:35.869727+00:00 to become allowed state ['success'] ...
[2025-03-13T16:23:14.306+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 16:15:35.869727+00:00 to become allowed state ['success'] ...
[2025-03-13T16:24:19.778+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: parse_mongo_to_sql_dag failed with failed states failed
[2025-03-13T16:24:19.784+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=web_scraping_dag, task_id=trigger_parse_dag, run_id=manual__2025-03-13T15:52:01.509950+00:00, execution_date=20250313T155201, start_date=20250313T161535, end_date=20250313T162419
[2025-03-13T16:24:19.808+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-13T16:24:19.809+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 143 for task trigger_parse_dag (parse_mongo_to_sql_dag failed with failed states failed; 6991)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: parse_mongo_to_sql_dag failed with failed states failed
[2025-03-13T16:24:19.828+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-13T16:24:19.846+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T16:24:19.848+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
